//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_Game_Maker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS_Game_Maker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AcceptIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("AcceptIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ActionBacker
        {
            get
            {
                object obj = ResourceManager.GetObject("ActionBacker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ActionBG
        {
            get
            {
                object obj = ResourceManager.GetObject("ActionBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ActionConditionalBG
        {
            get
            {
                object obj = ResourceManager.GetObject("ActionConditionalBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ActionEditIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ActionEditIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ActionIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ActionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static byte[] ActionWorks
        {
            get
            {
                object obj = ResourceManager.GetObject("ActionWorks", resourceCulture);
                return (byte[])obj;
            }
        }

        internal static System.Drawing.Bitmap AddFolderIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("AddFolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap AlarmIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("AlarmIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArgumentIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ArgumentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrayIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrayIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrowDown
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrowFadeRightIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowFadeRightIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrowUp
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BackgroundAddIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("BackgroundAddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BackgroundIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("BackgroundIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BarBG
        {
            get
            {
                object obj = ResourceManager.GetObject("BarBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BarBGSmall
        {
            get
            {
                object obj = ResourceManager.GetObject("BarBGSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BigFolderIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("BigFolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BigHBIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("BigHBIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BigMusicIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("BigMusicIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BigMusicIcon1
        {
            get
            {
                object obj = ResourceManager.GetObject("BigMusicIcon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BigPlayButton
        {
            get
            {
                object obj = ResourceManager.GetObject("BigPlayButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap BigSaveIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("BigSaveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClockIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ClockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Collision
        {
            get
            {
                object obj = ResourceManager.GetObject("Collision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap color
        {
            get
            {
                object obj = ResourceManager.GetObject("color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap CopyIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("CopyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Corners
        {
            get
            {
                object obj = ResourceManager.GetObject("Corners", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap CreateEventIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("CreateEventIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap CutIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("CutIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DeleteIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("DeleteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Icon DSGMIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("DSGMIcon", resourceCulture);
                return (System.Drawing.Icon)obj;
            }
        }

        internal static System.Drawing.Bitmap DSGMTopBanner
        {
            get
            {
                object obj = ResourceManager.GetObject("DSGMTopBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ExportSpriteStripButton
        {
            get
            {
                object obj = ResourceManager.GetObject("ExportSpriteStripButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ExportSpriteStripIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ExportSpriteStripIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static byte[] ExtraDBAS
        {
            get
            {
                object obj = ResourceManager.GetObject("ExtraDBAS", resourceCulture);
                return (byte[])obj;
            }
        }

        internal static System.Drawing.Bitmap FolderIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("FolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap FontIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("FontIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap GameSettingsIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("GameSettingsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InGameProBanner
        {
            get
            {
                object obj = ResourceManager.GetObject("InGameProBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InsertIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("InsertIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InternetIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("InternetIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap KeyDownIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("KeyDownIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap KeyDownIcon1
        {
            get
            {
                object obj = ResourceManager.GetObject("KeyDownIcon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap KeyIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("KeyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap LeftArrowSmall
        {
            get
            {
                object obj = ResourceManager.GetObject("LeftArrowSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ListIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ListIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap LockIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("LockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap MDIBG
        {
            get
            {
                object obj = ResourceManager.GetObject("MDIBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap NewIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("NewIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static byte[] NitroGraphics
        {
            get
            {
                object obj = ResourceManager.GetObject("NitroGraphics", resourceCulture);
                return (byte[])obj;
            }
        }

        internal static System.Drawing.Bitmap ObjectAddIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ObjectAddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ObjectIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ObjectIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap OpenIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap OpenLastIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenLastIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap OpenObjectIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenObjectIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap OptionsIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("OptionsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap OtherIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("OtherIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static byte[] PAGfx
        {
            get
            {
                object obj = ResourceManager.GetObject("PAGfx", resourceCulture);
                return (byte[])obj;
            }
        }

        internal static System.Drawing.Bitmap PasteIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("PasteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PathAddIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("PathAddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PathIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("PathIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PencilIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("PencilIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PlayButtonIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("PlayButtonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PlusIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("PlusIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ProBanner
        {
            get
            {
                object obj = ResourceManager.GetObject("ProBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap QuestionIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("QuestionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RedoIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("RedoIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RightArrowSmall
        {
            get
            {
                object obj = ResourceManager.GetObject("RightArrowSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RoomAddIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("RoomAddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RoomIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("RoomIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RoundedBlock
        {
            get
            {
                object obj = ResourceManager.GetObject("RoundedBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SaveAsIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SaveAsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SaveIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SaveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ScriptAddIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ScriptAddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ScriptExportIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ScriptExportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ScriptIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ScriptIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ScriptImportIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ScriptImportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SoundAddIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SoundAddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SoundIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SoundIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpriteAddIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SpriteAddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpriteIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SpriteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpriteMeasureIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SpriteMeasureIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpriteMoveIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("SpriteMoveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpriteSizesTable
        {
            get
            {
                object obj = ResourceManager.GetObject("SpriteSizesTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpriteSizesTable1
        {
            get
            {
                object obj = ResourceManager.GetObject("SpriteSizesTable1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StopButtonIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("StopButtonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StructureIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("StructureIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StylusIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("StylusIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap TestGameIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("TestGameIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap TestGameSaveIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("TestGameSaveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap TransformIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("TransformIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap UndoIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("UndoIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap UnlockIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("UnlockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap UpdateBigIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("UpdateBigIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VariableIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("VariableIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VariableManagerIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("VariableManagerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static byte[] WifiLibC
        {
            get
            {
                object obj = ResourceManager.GetObject("WifiLibC", resourceCulture);
                return (byte[])obj;
            }
        }

        internal static byte[] WifiLibH
        {
            get
            {
                object obj = ResourceManager.GetObject("WifiLibH", resourceCulture);
                return (byte[])obj;
            }
        }


    }
}
